name: CI

on:
  push:
    branches: [ release ]
  workflow_dispatch:

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          PACKAGEJSON_DIR: 'electron-app'
          target-branch: 'release'

      - name: Publish application
        run: npm run publish
