name: CI

on:
  push:
    branches: [ release ]
  workflow_dispatch:

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'electron-app'
        with:
          tag-prefix:  'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          target-branch: 'release'
          
      - name: npm install electron
        working-directory: ./electron-app
        run: npm install
        
      - name: npm install react
        working-directory: ./react-app
        run: npm install
        
      - name: Build
        working-directory: ./electron-app
        run: npm run build

      - name: Publish Application
        working-directory: ./electron-app
        run: npm run publish
