name: RELEASE

on:
  workflow_run:
    workflows: ["BUMP"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2      
          
      - name: npm install electron
        working-directory: ./electron-app
        run: npm install
        
      - name: npm install react
        working-directory: ./react-app
        run: npm install
        
      - name: Build
        working-directory: ./electron-app
        run: npm run build

      - name: Publish Application
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_TOKEN }}
        working-directory: ./electron-app
        run: npm run publish
